---
# Urgences

# Commutateur neuf intégré au stack existant en tant que membre 2.
vsf:
  member: 2
  link_interfaces:
    - 2/1/49
    - 2/1/50

# Agrégations à créer, relevées port par port sur site.
lags:
  - id: 12
    description: "Bornes Wi-Fi, urgences"
    member: 2
    interfaces:
      - 2/1/13
      - 2/1/14
    native_vlan: 50
    tagged_vlans: [50, 60]
